# Notebook 17: Mystery.csv file:

The file mystery.csv that is included with this notebook contains 1000 rows and 11 columns. Assume that the **first column** contains measurements of some particular feature that we are interested in for 1000 different people, one person per row. Each of the other 10 columns contains measurements of some other properties. We would like to know which of these other 10 properties the number in the first column depends on.

For example, say the number in the first column represents blood pressure, and the other columns represent things like sodium intake, exercise amount, alcoholic beverages consumed, etc. We want to know wich of these variables has an effect on blood pressure.

The file mystery.csv was constructed so that the first column depends on a **randomly chosen subset of two of the other columns**. The first column was constructed as follows:<br>

first column = (some random slope)x(mystery column 1) + (some other random slope)x(mystery column 2).

Your job is to identify the two mystery columns (in other words, what other two columns does the first column depend on?)

You should use **two different independent methods** to arrive at an answer, and then check that both methods give the same answer for the mystery columns.

I am not providing any starter code this time, you should do this on your own, although you are certainly free to go back and look at previous notebooks as much as you want. Have fun!

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
###YOUR CODE FOR YOUR FIRST METHOD HERE!
from google.colab import drive
drive.mount ('/content/drive')
df = pd.read_csv('drive/My Drive/Notebook17/mystery.csv')

Mounted at /content/drive

In [3]:
df

,1,2,3,4,5,6,7,8,9,10,11
0,5.652125,0.752553,0.339883,0.449144,0.815833,0.545241,0.808239,0.710138,0.632295,0.058983,0.758632
1,5.891676,0.281487,0.102962,0.663073,0.988164,0.463945,0.170256,0.725950,0.405762,0.292256,0.864050
2,6.630418,0.349831,0.581237,0.750683,0.914321,0.833289,0.089194,0.055036,0.820298,0.720616,0.491821
3,2.194120,0.379786,0.530133,0.395970,0.099728,0.626749,0.366270,0.029910,0.644468,0.430018,0.099281
4,2.673166,0.317216,0.284984,0.362683,0.190207,0.227675,0.781165,0.632480,0.658828,0.200687,0.592961
...,...,...,...,...,...,...,...,...,...,...,...
995,5.151652,0.548306,0.374388,0.214185,0.645091,0.094010,0.892530,0.440616,0.757457,0.843647,0.785939
996,2.641228,0.967959,0.322885,0.431504,0.174037,0.750243,0.065355,0.826209,0.676514,0.505690,0.055981
997,4.458164,0.110144,0.009590,0.959277,0.857050,0.268563,0.448749,0.696127,0.105999,0.241347,0.083553
998,7.176167,0.652028,0.806145,0.900073,0.932473,0.981862,0.428932,0.866204,0.992834,0.124801,0.068023
999,5.783894,0.286394,0.367281,0.033467,0.712200,0.503378,0.943456,0.532108,0.872595,0.758242,0.300371

In [46]:
# first column = (some random slope)x(mystery column 1) + (some other random slope)x(mystery column 2).
# Your job is to identify the two mystery columns (in other words, what other two columns does the first column depend on?)

correlations = df.corr().iloc[0, 1:]  # Get correlations with column 0, excluding itself

top_2_indices = correlations.argsort()[-2:][::-1]  # Get indices of top 2 values

print(correlations.iloc[top_2_indices])

5    0.889395
9    0.527487
Name: 1, dtype: float64

top 2 are 5 and 9

In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [6]:
df2 = df.drop(columns=df.columns[0])
df2

,2,3,4,5,6,7,8,9,10,11
0,0.752553,0.339883,0.449144,0.815833,0.545241,0.808239,0.710138,0.632295,0.058983,0.758632
1,0.281487,0.102962,0.663073,0.988164,0.463945,0.170256,0.725950,0.405762,0.292256,0.864050
2,0.349831,0.581237,0.750683,0.914321,0.833289,0.089194,0.055036,0.820298,0.720616,0.491821
3,0.379786,0.530133,0.395970,0.099728,0.626749,0.366270,0.029910,0.644468,0.430018,0.099281
4,0.317216,0.284984,0.362683,0.190207,0.227675,0.781165,0.632480,0.658828,0.200687,0.592961
...,...,...,...,...,...,...,...,...,...,...
995,0.548306,0.374388,0.214185,0.645091,0.094010,0.892530,0.440616,0.757457,0.843647,0.785939
996,0.967959,0.322885,0.431504,0.174037,0.750243,0.065355,0.826209,0.676514,0.505690,0.055981
997,0.110144,0.009590,0.959277,0.857050,0.268563,0.448749,0.696127,0.105999,0.241347,0.083553
998,0.652028,0.806145,0.900073,0.932473,0.981862,0.428932,0.866204,0.992834,0.124801,0.068023
999,0.286394,0.367281,0.033467,0.712200,0.503378,0.943456,0.532108,0.872595,0.758242,0.300371

In [7]:
X = df2

In [22]:
y = column_1 = df['1']
y

0      5.652125
1      5.891676
2      6.630418
3      2.194120
4      2.673166
         ...
995    5.151652
996    2.641228
997    4.458164
998    7.176167
999    5.783894
Name: 1, Length: 1000, dtype: float64

In [9]:
regressor = LinearRegression()
regressor.fit(X, y)

LinearRegression()

In [10]:
print(regressor.coef_)

[ 2.75580011e-15  6.88338275e-15 -3.44169138e-15  4.87396283e+00
 -1.94289029e-15  4.61870125e-15  3.08780779e-16  2.65032023e+00
  4.66293670e-15 -2.55004351e-16]

In [47]:
model = LinearRegression()
model.fit(X, y)\

coefs = pd.Series(model.coef_, index=X.columns)

top_2 = np.argsort(np.abs(coefs))[-2:][::-1]  # Get indices of the top 2 in descending order
top_2_coefs = coefs.iloc[top_2]

top_2_coefs

5    4.873963
9    2.650320
dtype: float64